
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdma.h"

/*
* The configuration table for devices
*/

XDma_Config XDma_ConfigTable[XPAR_XDMA_NUM_INSTANCES] =
{
	{
		XPAR_DMA_0_DEVICE_ID,
		XPAR_DMA_0_S_AXI_CONTROL_BASEADDR
	}
};


